xsafe: true
lsi: false
pygments: true
exclude: ['Makefile','link-checker-crawled-pages.pstore','ERRORs.txt','Gemfile','Gemfile.lock']
include: ['.htaccess','sites']
permalink: pretty
pagination: 5
desination: _site/Blog
pagination_path: "/Blog/page:num/"