xsafe: true
lsi: false
pygments: true
exclude: ['Makefile','link-checker-crawled-pages.pstore','ERRORs.txt','Gemfile','Gemfile.lock']
include: ['.htaccess','sites']
permalink: pretty
paginate: 5
paginate_path: "/Blog/page:num/"